services:
  web:
    build:
      context: .
    image: quakewatch-web:1.0.0 # Tag with version 1.0.0
    ports:
      - "${APP_PORT}:${APP_PORT}" # Uses environment variable for port mapping
    environment:
      APP_PORT: ${APP_PORT}
      #FLASK_ENV: development # Remove for production
    healthcheck:
      test: [ "CMD", "python", "-c", "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('127.0.0.1', ${APP_PORT})); s.close(); exit(0)" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - quake_data:/data # Mount quake_data volume to /data
volumes: # Define the named volume
  quake_data: